const barnyardFilters = {
  breed: {
    name: 'breed',
    label: 'Breed',
    display: true,
    options: [
      {
        value: 'Alpaca',
        label: 'Alpaca',
        long_label: 'Alpaca',
        facet_value: '557',
        default: false,
      },
      {
        value: 'Alpine',
        label: 'Alpine',
        long_label: 'Alpine',
        facet_value: '567',
        default: false,
      },
      {
        value: 'Angora',
        label: 'Angora',
        long_label: 'Angora',
        facet_value: '680',
        default: false,
      },
      {
        value: 'Angus',
        label: 'Angus',
        long_label: 'Angus',
        facet_value: '558',
        default: false,
      },
      {
        value: 'Barbados',
        label: 'Barbados',
        long_label: 'Barbados',
        facet_value: '562',
        default: false,
      },
      {
        value: 'Boer',
        label: 'Boer',
        long_label: 'Boer',
        facet_value: '681',
        default: false,
      },
      {
        value: 'Cow',
        label: 'Cow',
        long_label: 'Cow',
        facet_value: '561',
        default: false,
      },
      {
        value: 'Duroc',
        label: 'Duroc',
        long_label: 'Duroc',
        facet_value: '688',
        default: false,
      },
      {
        value: 'Goat',
        label: 'Goat',
        long_label: 'Goat',
        facet_value: '570',
        default: false,
      },
      {
        value: 'Hampshire',
        label: 'Hampshire',
        long_label: 'Hampshire',
        facet_value: '689',
        default: false,
      },
      {
        value: 'Holstein',
        label: 'Holstein',
        long_label: 'Holstein',
        facet_value: '559',
        default: false,
      },
      {
        value: 'Jersey',
        label: 'Jersey',
        long_label: 'Jersey',
        facet_value: '560',
        default: false,
      },
      {
        value: 'LaMancha',
        label: 'LaMancha',
        long_label: 'LaMancha',
        facet_value: '682',
        default: false,
      },
      {
        value: 'Landrace',
        label: 'Landrace',
        long_label: 'Landrace',
        facet_value: '690',
        default: false,
      },
      {
        value: 'Llama',
        label: 'Llama',
        long_label: 'Llama',
        facet_value: '556',
        default: false,
      },
      {
        value: 'Merino',
        label: 'Merino',
        long_label: 'Merino',
        facet_value: '564',
        default: false,
      },
      {
        value: 'Mouflon',
        label: 'Mouflon',
        long_label: 'Mouflon',
        facet_value: '565',
        default: false,
      },
      {
        value: 'Myotonic / Fainting',
        label: 'Myotonic / Fainting',
        long_label: 'Myotonic / Fainting',
        facet_value: '683',
        default: false,
      },
      {
        value: 'Nigerian Dwarf',
        label: 'Nigerian Dwarf',
        long_label: 'Nigerian Dwarf',
        facet_value: '569',
        default: false,
      },
      {
        value: 'Nubian',
        label: 'Nubian',
        long_label: 'Nubian',
        facet_value: '684',
        default: false,
      },
      {
        value: 'Oberhasli',
        label: 'Oberhasli',
        long_label: 'Oberhasli',
        facet_value: '685',
        default: false,
      },
      {
        value: 'Pig',
        label: 'Pig',
        long_label: 'Pig',
        facet_value: '571',
        default: false,
      },
      {
        value: 'Pot Bellied',
        label: 'Pot Bellied',
        long_label: 'Pot Bellied',
        facet_value: '572',
        default: false,
      },
      {
        value: 'Pygmy',
        label: 'Pygmy',
        long_label: 'Pygmy',
        facet_value: '568',
        default: false,
      },
      {
        value: 'Saanen',
        label: 'Saanen',
        long_label: 'Saanen',
        facet_value: '686',
        default: false,
      },
      {
        value: 'Sheep',
        label: 'Sheep',
        long_label: 'Sheep',
        facet_value: '566',
        default: false,
      },
      {
        value: 'Shetland',
        label: 'Shetland',
        long_label: 'Shetland',
        facet_value: '563',
        default: false,
      },
      {
        value: 'Toggenburg',
        label: 'Toggenburg',
        long_label: 'Toggenburg',
        facet_value: '687',
        default: false,
      },
      {
        value: 'Vietnamese Pot Bellied',
        label: 'Vietnamese Pot Bellied',
        long_label: 'Vietnamese Pot Bellied',
        facet_value: '573',
        default: false,
      },
      {
        value: 'Yorkshire',
        label: 'Yorkshire',
        long_label: 'Yorkshire',
        facet_value: '691',
        default: false,
      },
    ],
  },
};

export default barnyardFilters;
