const dogFilters = {
  age: {
    name: 'age',
    label: 'Age',
    display: true,
    options: [
      {
        value: 'Baby',
        label: 'Puppy',
        long_label: 'Puppy',
        default: false,
      },
      {
        value: 'Young',
        label: 'Young',
        long_label: 'Young',
        default: false,
      },
      {
        value: 'Adult',
        label: 'Adult',
        long_label: 'Adult',
        default: false,
      },
      {
        value: 'Senior',
        label: 'Senior',
        long_label: 'Senior',
        default: false,
      },
    ],
  },
  breed: {
    name: 'breed',
    label: 'Breed',
    display: true,
    options: [
      {
        value: 'Affenpinscher',
        label: 'Affenpinscher',
        long_label: 'Affenpinscher',
        facet_value: '172',
        default: false,
      },
      {
        value: 'Afghan Hound',
        label: 'Afghan Hound',
        long_label: 'Afghan Hound',
        facet_value: '173',
        default: false,
      },
      {
        value: 'Airedale Terrier',
        label: 'Airedale Terrier',
        long_label: 'Airedale Terrier',
        facet_value: '174',
        default: false,
      },
      {
        value: 'Akbash',
        label: 'Akbash',
        long_label: 'Akbash',
        facet_value: '175',
        default: false,
      },
      {
        value: 'Akita',
        label: 'Akita',
        long_label: 'Akita',
        facet_value: '176',
        default: false,
      },
      {
        value: 'Alaskan Malamute',
        label: 'Alaskan Malamute',
        long_label: 'Alaskan Malamute',
        facet_value: '177',
        default: false,
      },
      {
        value: 'American Bulldog',
        label: 'American Bulldog',
        long_label: 'American Bulldog',
        facet_value: '178',
        default: false,
      },
      {
        value: 'American Eskimo Dog',
        label: 'American Eskimo Dog',
        long_label: 'American Eskimo Dog',
        facet_value: '179',
        default: false,
      },
      {
        value: 'American Foxhound',
        label: 'American Foxhound',
        long_label: 'American Foxhound',
        facet_value: '710',
        default: false,
      },
      {
        value: 'American Hairless Terrier',
        label: 'American Hairless Terrier',
        long_label: 'American Hairless Terrier',
        facet_value: '180',
        default: false,
      },
      {
        value: 'American Staffordshire Terrier',
        label: 'American Staffordshire Terrier',
        long_label: 'American Staffordshire Terrier',
        facet_value: '181',
        default: false,
      },
      {
        value: 'American Water Spaniel',
        label: 'American Water Spaniel',
        long_label: 'American Water Spaniel',
        facet_value: '182',
        default: false,
      },
      {
        value: 'Anatolian Shepherd',
        label: 'Anatolian Shepherd',
        long_label: 'Anatolian Shepherd',
        facet_value: '183',
        default: false,
      },
      {
        value: 'Appenzell Mountain Dog',
        label: 'Appenzell Mountain Dog',
        long_label: 'Appenzell Mountain Dog',
        facet_value: '184',
        default: false,
      },
      {
        value: 'Australian Cattle Dog / Blue Heeler',
        label: 'Australian Cattle Dog / Blue Heeler',
        long_label: 'Australian Cattle Dog / Blue Heeler',
        facet_value: '185',
        default: false,
      },
      {
        value: 'Australian Kelpie',
        label: 'Australian Kelpie',
        long_label: 'Australian Kelpie',
        facet_value: '186',
        default: false,
      },
      {
        value: 'Australian Shepherd',
        label: 'Australian Shepherd',
        long_label: 'Australian Shepherd',
        facet_value: '187',
        default: false,
      },
      {
        value: 'Australian Terrier',
        label: 'Australian Terrier',
        long_label: 'Australian Terrier',
        facet_value: '188',
        default: false,
      },
      {
        value: 'Basenji',
        label: 'Basenji',
        long_label: 'Basenji',
        facet_value: '189',
        default: false,
      },
      {
        value: 'Basset Hound',
        label: 'Basset Hound',
        long_label: 'Basset Hound',
        facet_value: '190',
        default: false,
      },
      {
        value: 'Beagle',
        label: 'Beagle',
        long_label: 'Beagle',
        facet_value: '191',
        default: false,
      },
      {
        value: 'Bearded Collie',
        label: 'Bearded Collie',
        long_label: 'Bearded Collie',
        facet_value: '192',
        default: false,
      },
      {
        value: 'Beauceron',
        label: 'Beauceron',
        long_label: 'Beauceron',
        facet_value: '193',
        default: false,
      },
      {
        value: 'Bedlington Terrier',
        label: 'Bedlington Terrier',
        long_label: 'Bedlington Terrier',
        facet_value: '194',
        default: false,
      },
      {
        value: 'Belgian Shepherd / Laekenois',
        label: 'Belgian Shepherd / Laekenois',
        long_label: 'Belgian Shepherd / Laekenois',
        facet_value: '196',
        default: false,
      },
      {
        value: 'Belgian Shepherd / Malinois',
        label: 'Belgian Shepherd / Malinois',
        long_label: 'Belgian Shepherd / Malinois',
        facet_value: '197',
        default: false,
      },
      {
        value: 'Belgian Shepherd / Sheepdog',
        label: 'Belgian Shepherd / Sheepdog',
        long_label: 'Belgian Shepherd / Sheepdog',
        facet_value: '195',
        default: false,
      },
      {
        value: 'Belgian Shepherd / Tervuren',
        label: 'Belgian Shepherd / Tervuren',
        long_label: 'Belgian Shepherd / Tervuren',
        facet_value: '198',
        default: false,
      },
      {
        value: 'Bernese Mountain Dog',
        label: 'Bernese Mountain Dog',
        long_label: 'Bernese Mountain Dog',
        facet_value: '199',
        default: false,
      },
      {
        value: 'Bichon Frise',
        label: 'Bichon Frise',
        long_label: 'Bichon Frise',
        facet_value: '200',
        default: false,
      },
      {
        value: 'Black and Tan Coonhound',
        label: 'Black and Tan Coonhound',
        long_label: 'Black and Tan Coonhound',
        facet_value: '201',
        default: false,
      },
      {
        value: 'Black Labrador Retriever',
        label: 'Black Labrador Retriever',
        long_label: 'Black Labrador Retriever',
        facet_value: '202',
        default: false,
      },
      {
        value: 'Black Mouth Cur',
        label: 'Black Mouth Cur',
        long_label: 'Black Mouth Cur',
        facet_value: '203',
        default: false,
      },
      {
        value: 'Black Russian Terrier',
        label: 'Black Russian Terrier',
        long_label: 'Black Russian Terrier',
        facet_value: '204',
        default: false,
      },
      {
        value: 'Bloodhound',
        label: 'Bloodhound',
        long_label: 'Bloodhound',
        facet_value: '205',
        default: false,
      },
      {
        value: 'Blue Lacy',
        label: 'Blue Lacy',
        long_label: 'Blue Lacy',
        facet_value: '206',
        default: false,
      },
      {
        value: 'Bluetick Coonhound',
        label: 'Bluetick Coonhound',
        long_label: 'Bluetick Coonhound',
        facet_value: '207',
        default: false,
      },
      {
        value: 'Boerboel',
        label: 'Boerboel',
        long_label: 'Boerboel',
        facet_value: '208',
        default: false,
      },
      {
        value: 'Bolognese',
        label: 'Bolognese',
        long_label: 'Bolognese',
        facet_value: '209',
        default: false,
      },
      {
        value: 'Border Collie',
        label: 'Border Collie',
        long_label: 'Border Collie',
        facet_value: '210',
        default: false,
      },
      {
        value: 'Border Terrier',
        label: 'Border Terrier',
        long_label: 'Border Terrier',
        facet_value: '211',
        default: false,
      },
      {
        value: 'Borzoi',
        label: 'Borzoi',
        long_label: 'Borzoi',
        facet_value: '212',
        default: false,
      },
      {
        value: 'Boston Terrier',
        label: 'Boston Terrier',
        long_label: 'Boston Terrier',
        facet_value: '213',
        default: false,
      },
      {
        value: 'Bouvier des Flandres',
        label: 'Bouvier des Flandres',
        long_label: 'Bouvier des Flandres',
        facet_value: '214',
        default: false,
      },
      {
        value: 'Boxer',
        label: 'Boxer',
        long_label: 'Boxer',
        facet_value: '215',
        default: false,
      },
      {
        value: 'Boykin Spaniel',
        label: 'Boykin Spaniel',
        long_label: 'Boykin Spaniel',
        facet_value: '216',
        default: false,
      },
      {
        value: 'Briard',
        label: 'Briard',
        long_label: 'Briard',
        facet_value: '217',
        default: false,
      },
      {
        value: 'Brittany Spaniel',
        label: 'Brittany Spaniel',
        long_label: 'Brittany Spaniel',
        facet_value: '218',
        default: false,
      },
      {
        value: 'Brussels Griffon',
        label: 'Brussels Griffon',
        long_label: 'Brussels Griffon',
        facet_value: '219',
        default: false,
      },
      {
        value: 'Bull Terrier',
        label: 'Bull Terrier',
        long_label: 'Bull Terrier',
        facet_value: '220',
        default: false,
      },
      {
        value: 'Bullmastiff',
        label: 'Bullmastiff',
        long_label: 'Bullmastiff',
        facet_value: '221',
        default: false,
      },
      {
        value: 'Cairn Terrier',
        label: 'Cairn Terrier',
        long_label: 'Cairn Terrier',
        facet_value: '222',
        default: false,
      },
      {
        value: 'Canaan Dog',
        label: 'Canaan Dog',
        long_label: 'Canaan Dog',
        facet_value: '223',
        default: false,
      },
      {
        value: 'Cane Corso',
        label: 'Cane Corso',
        long_label: 'Cane Corso',
        facet_value: '224',
        default: false,
      },
      {
        value: 'Cardigan Welsh Corgi',
        label: 'Cardigan Welsh Corgi',
        long_label: 'Cardigan Welsh Corgi',
        facet_value: '398',
        default: false,
      },
      {
        value: 'Carolina Dog',
        label: 'Carolina Dog',
        long_label: 'Carolina Dog',
        facet_value: '225',
        default: false,
      },
      {
        value: 'Catahoula Leopard Dog',
        label: 'Catahoula Leopard Dog',
        long_label: 'Catahoula Leopard Dog',
        facet_value: '226',
        default: false,
      },
      {
        value: 'Cattle Dog',
        label: 'Cattle Dog',
        long_label: 'Cattle Dog',
        facet_value: '227',
        default: false,
      },
      {
        value: 'Caucasian Sheepdog / Caucasian Ovtcharka',
        label: 'Caucasian Sheepdog / Caucasian Ovtcharka',
        long_label: 'Caucasian Sheepdog / Caucasian Ovtcharka',
        facet_value: '228',
        default: false,
      },
      {
        value: 'Cavalier King Charles Spaniel',
        label: 'Cavalier King Charles Spaniel',
        long_label: 'Cavalier King Charles Spaniel',
        facet_value: '229',
        default: false,
      },
      {
        value: 'Chesapeake Bay Retriever',
        label: 'Chesapeake Bay Retriever',
        long_label: 'Chesapeake Bay Retriever',
        facet_value: '230',
        default: false,
      },
      {
        value: 'Chihuahua',
        label: 'Chihuahua',
        long_label: 'Chihuahua',
        facet_value: '231',
        default: false,
      },
      {
        value: 'Chinese Crested Dog',
        label: 'Chinese Crested Dog',
        long_label: 'Chinese Crested Dog',
        facet_value: '232',
        default: false,
      },
      {
        value: 'Chinese Foo Dog',
        label: 'Chinese Foo Dog',
        long_label: 'Chinese Foo Dog',
        facet_value: '233',
        default: false,
      },
      {
        value: 'Chinook',
        label: 'Chinook',
        long_label: 'Chinook',
        facet_value: '234',
        default: false,
      },
      {
        value: 'Chocolate Labrador Retriever',
        label: 'Chocolate Labrador Retriever',
        long_label: 'Chocolate Labrador Retriever',
        facet_value: '235',
        default: false,
      },
      {
        value: 'Chow Chow',
        label: 'Chow Chow',
        long_label: 'Chow Chow',
        facet_value: '236',
        default: false,
      },
      {
        value: "Cirneco dell'Etna",
        label: "Cirneco dell'Etna",
        long_label: "Cirneco dell'Etna",
        facet_value: '237',
        default: false,
      },
      {
        value: 'Clumber Spaniel',
        label: 'Clumber Spaniel',
        long_label: 'Clumber Spaniel',
        facet_value: '238',
        default: false,
      },
      {
        value: 'Cockapoo',
        label: 'Cockapoo',
        long_label: 'Cockapoo',
        facet_value: '239',
        default: false,
      },
      {
        value: 'Cocker Spaniel',
        label: 'Cocker Spaniel',
        long_label: 'Cocker Spaniel',
        facet_value: '240',
        default: false,
      },
      {
        value: 'Collie',
        label: 'Collie',
        long_label: 'Collie',
        facet_value: '241',
        default: false,
      },
      {
        value: 'Coonhound',
        label: 'Coonhound',
        long_label: 'Coonhound',
        facet_value: '242',
        default: false,
      },
      {
        value: 'Corgi',
        label: 'Corgi',
        long_label: 'Corgi',
        facet_value: '243',
        default: false,
      },
      {
        value: 'Coton de Tulear',
        label: 'Coton de Tulear',
        long_label: 'Coton de Tulear',
        facet_value: '244',
        default: false,
      },
      {
        value: 'Curly-Coated Retriever',
        label: 'Curly-Coated Retriever',
        long_label: 'Curly-Coated Retriever',
        facet_value: '245',
        default: false,
      },
      {
        value: 'Dachshund',
        label: 'Dachshund',
        long_label: 'Dachshund',
        facet_value: '246',
        default: false,
      },
      {
        value: 'Dalmatian',
        label: 'Dalmatian',
        long_label: 'Dalmatian',
        facet_value: '247',
        default: false,
      },
      {
        value: 'Dandie Dinmont Terrier',
        label: 'Dandie Dinmont Terrier',
        long_label: 'Dandie Dinmont Terrier',
        facet_value: '248',
        default: false,
      },
      {
        value: 'Doberman Pinscher',
        label: 'Doberman Pinscher',
        long_label: 'Doberman Pinscher',
        facet_value: '249',
        default: false,
      },
      {
        value: 'Dogo Argentino',
        label: 'Dogo Argentino',
        long_label: 'Dogo Argentino',
        facet_value: '250',
        default: false,
      },
      {
        value: 'Dogue de Bordeaux',
        label: 'Dogue de Bordeaux',
        long_label: 'Dogue de Bordeaux',
        facet_value: '251',
        default: false,
      },
      {
        value: 'Dutch Shepherd',
        label: 'Dutch Shepherd',
        long_label: 'Dutch Shepherd',
        facet_value: '252',
        default: false,
      },
      {
        value: 'English Bulldog',
        label: 'English Bulldog',
        long_label: 'English Bulldog',
        facet_value: '253',
        default: false,
      },
      {
        value: 'English Cocker Spaniel',
        label: 'English Cocker Spaniel',
        long_label: 'English Cocker Spaniel',
        facet_value: '254',
        default: false,
      },
      {
        value: 'English Coonhound',
        label: 'English Coonhound',
        long_label: 'English Coonhound',
        facet_value: '255',
        default: false,
      },
      {
        value: 'English Foxhound',
        label: 'English Foxhound',
        long_label: 'English Foxhound',
        facet_value: '713',
        default: false,
      },
      {
        value: 'English Pointer',
        label: 'English Pointer',
        long_label: 'English Pointer',
        facet_value: '256',
        default: false,
      },
      {
        value: 'English Setter',
        label: 'English Setter',
        long_label: 'English Setter',
        facet_value: '257',
        default: false,
      },
      {
        value: 'English Shepherd',
        label: 'English Shepherd',
        long_label: 'English Shepherd',
        facet_value: '258',
        default: false,
      },
      {
        value: 'English Springer Spaniel',
        label: 'English Springer Spaniel',
        long_label: 'English Springer Spaniel',
        facet_value: '259',
        default: false,
      },
      {
        value: 'English Toy Spaniel',
        label: 'English Toy Spaniel',
        long_label: 'English Toy Spaniel',
        facet_value: '260',
        default: false,
      },
      {
        value: 'Entlebucher',
        label: 'Entlebucher',
        long_label: 'Entlebucher',
        facet_value: '261',
        default: false,
      },
      {
        value: 'Eskimo Dog',
        label: 'Eskimo Dog',
        long_label: 'Eskimo Dog',
        facet_value: '262',
        default: false,
      },
      {
        value: 'Feist',
        label: 'Feist',
        long_label: 'Feist',
        facet_value: '263',
        default: false,
      },
      {
        value: 'Field Spaniel',
        label: 'Field Spaniel',
        long_label: 'Field Spaniel',
        facet_value: '264',
        default: false,
      },
      {
        value: 'Fila Brasileiro',
        label: 'Fila Brasileiro',
        long_label: 'Fila Brasileiro',
        facet_value: '265',
        default: false,
      },
      {
        value: 'Finnish Lapphund',
        label: 'Finnish Lapphund',
        long_label: 'Finnish Lapphund',
        facet_value: '266',
        default: false,
      },
      {
        value: 'Finnish Spitz',
        label: 'Finnish Spitz',
        long_label: 'Finnish Spitz',
        facet_value: '267',
        default: false,
      },
      {
        value: 'Flat-Coated Retriever',
        label: 'Flat-Coated Retriever',
        long_label: 'Flat-Coated Retriever',
        facet_value: '268',
        default: false,
      },
      {
        value: 'Fox Terrier',
        label: 'Fox Terrier',
        long_label: 'Fox Terrier',
        facet_value: '269',
        default: false,
      },
      {
        value: 'Foxhound',
        label: 'Foxhound',
        long_label: 'Foxhound',
        facet_value: '270',
        default: false,
      },
      {
        value: 'French Bulldog',
        label: 'French Bulldog',
        long_label: 'French Bulldog',
        facet_value: '271',
        default: false,
      },
      {
        value: 'Galgo Spanish Greyhound',
        label: 'Galgo Spanish Greyhound',
        long_label: 'Galgo Spanish Greyhound',
        facet_value: '272',
        default: false,
      },
      {
        value: 'German Pinscher',
        label: 'German Pinscher',
        long_label: 'German Pinscher',
        facet_value: '273',
        default: false,
      },
      {
        value: 'German Shepherd Dog',
        label: 'German Shepherd Dog',
        long_label: 'German Shepherd Dog',
        facet_value: '274',
        default: false,
      },
      {
        value: 'German Shorthaired Pointer',
        label: 'German Shorthaired Pointer',
        long_label: 'German Shorthaired Pointer',
        facet_value: '275',
        default: false,
      },
      {
        value: 'German Spitz',
        label: 'German Spitz',
        long_label: 'German Spitz',
        facet_value: '276',
        default: false,
      },
      {
        value: 'German Wirehaired Pointer',
        label: 'German Wirehaired Pointer',
        long_label: 'German Wirehaired Pointer',
        facet_value: '277',
        default: false,
      },
      {
        value: 'Giant Schnauzer',
        label: 'Giant Schnauzer',
        long_label: 'Giant Schnauzer',
        facet_value: '278',
        default: false,
      },
      {
        value: 'Glen of Imaal Terrier',
        label: 'Glen of Imaal Terrier',
        long_label: 'Glen of Imaal Terrier',
        facet_value: '279',
        default: false,
      },
      {
        value: 'Golden Retriever',
        label: 'Golden Retriever',
        long_label: 'Golden Retriever',
        facet_value: '280',
        default: false,
      },
      {
        value: 'Gordon Setter',
        label: 'Gordon Setter',
        long_label: 'Gordon Setter',
        facet_value: '281',
        default: false,
      },
      {
        value: 'Great Dane',
        label: 'Great Dane',
        long_label: 'Great Dane',
        facet_value: '282',
        default: false,
      },
      {
        value: 'Great Pyrenees',
        label: 'Great Pyrenees',
        long_label: 'Great Pyrenees',
        facet_value: '283',
        default: false,
      },
      {
        value: 'Greater Swiss Mountain Dog',
        label: 'Greater Swiss Mountain Dog',
        long_label: 'Greater Swiss Mountain Dog',
        facet_value: '284',
        default: false,
      },
      {
        value: 'Greyhound',
        label: 'Greyhound',
        long_label: 'Greyhound',
        facet_value: '285',
        default: false,
      },
      {
        value: 'Hamiltonstovare',
        label: 'Hamiltonstovare',
        long_label: 'Hamiltonstovare',
        facet_value: '692',
        default: false,
      },
      {
        value: 'Harrier',
        label: 'Harrier',
        long_label: 'Harrier',
        facet_value: '286',
        default: false,
      },
      {
        value: 'Havanese',
        label: 'Havanese',
        long_label: 'Havanese',
        facet_value: '287',
        default: false,
      },
      {
        value: 'Hound',
        label: 'Hound',
        long_label: 'Hound',
        facet_value: '288',
        default: false,
      },
      {
        value: 'Hovawart',
        label: 'Hovawart',
        long_label: 'Hovawart',
        facet_value: '289',
        default: false,
      },
      {
        value: 'Husky',
        label: 'Husky',
        long_label: 'Husky',
        facet_value: '290',
        default: false,
      },
      {
        value: 'Ibizan Hound',
        label: 'Ibizan Hound',
        long_label: 'Ibizan Hound',
        facet_value: '291',
        default: false,
      },
      {
        value: 'Icelandic Sheepdog',
        label: 'Icelandic Sheepdog',
        long_label: 'Icelandic Sheepdog',
        facet_value: '679',
        default: false,
      },
      {
        value: 'Illyrian Sheepdog',
        label: 'Illyrian Sheepdog',
        long_label: 'Illyrian Sheepdog',
        facet_value: '292',
        default: false,
      },
      {
        value: 'Irish Setter',
        label: 'Irish Setter',
        long_label: 'Irish Setter',
        facet_value: '293',
        default: false,
      },
      {
        value: 'Irish Terrier',
        label: 'Irish Terrier',
        long_label: 'Irish Terrier',
        facet_value: '294',
        default: false,
      },
      {
        value: 'Irish Water Spaniel',
        label: 'Irish Water Spaniel',
        long_label: 'Irish Water Spaniel',
        facet_value: '295',
        default: false,
      },
      {
        value: 'Irish Wolfhound',
        label: 'Irish Wolfhound',
        long_label: 'Irish Wolfhound',
        facet_value: '296',
        default: false,
      },
      {
        value: 'Italian Greyhound',
        label: 'Italian Greyhound',
        long_label: 'Italian Greyhound',
        facet_value: '297',
        default: false,
      },
      {
        value: 'Jack Russell Terrier',
        label: 'Jack Russell Terrier',
        long_label: 'Jack Russell Terrier',
        facet_value: '299',
        default: false,
      },
      {
        value: 'Japanese Chin',
        label: 'Japanese Chin',
        long_label: 'Japanese Chin',
        facet_value: '301',
        default: false,
      },
      {
        value: 'Jindo',
        label: 'Jindo',
        long_label: 'Jindo',
        facet_value: '302',
        default: false,
      },
      {
        value: 'Kai Dog',
        label: 'Kai Dog',
        long_label: 'Kai Dog',
        facet_value: '303',
        default: false,
      },
      {
        value: 'Karelian Bear Dog',
        label: 'Karelian Bear Dog',
        long_label: 'Karelian Bear Dog',
        facet_value: '304',
        default: false,
      },
      {
        value: 'Keeshond',
        label: 'Keeshond',
        long_label: 'Keeshond',
        facet_value: '305',
        default: false,
      },
      {
        value: 'Kerry Blue Terrier',
        label: 'Kerry Blue Terrier',
        long_label: 'Kerry Blue Terrier',
        facet_value: '306',
        default: false,
      },
      {
        value: 'Kishu',
        label: 'Kishu',
        long_label: 'Kishu',
        facet_value: '307',
        default: false,
      },
      {
        value: 'Klee Kai',
        label: 'Klee Kai',
        long_label: 'Klee Kai',
        facet_value: '308',
        default: false,
      },
      {
        value: 'Komondor',
        label: 'Komondor',
        long_label: 'Komondor',
        facet_value: '309',
        default: false,
      },
      {
        value: 'Kuvasz',
        label: 'Kuvasz',
        long_label: 'Kuvasz',
        facet_value: '310',
        default: false,
      },
      {
        value: 'Kyi Leo',
        label: 'Kyi Leo',
        long_label: 'Kyi Leo',
        facet_value: '311',
        default: false,
      },
      {
        value: 'Labrador Retriever',
        label: 'Labrador Retriever',
        long_label: 'Labrador Retriever',
        facet_value: '312',
        default: false,
      },
      {
        value: 'Lakeland Terrier',
        label: 'Lakeland Terrier',
        long_label: 'Lakeland Terrier',
        facet_value: '313',
        default: false,
      },
      {
        value: 'Lancashire Heeler',
        label: 'Lancashire Heeler',
        long_label: 'Lancashire Heeler',
        facet_value: '314',
        default: false,
      },
      {
        value: 'Leonberger',
        label: 'Leonberger',
        long_label: 'Leonberger',
        facet_value: '315',
        default: false,
      },
      {
        value: 'Lhasa Apso',
        label: 'Lhasa Apso',
        long_label: 'Lhasa Apso',
        facet_value: '316',
        default: false,
      },
      {
        value: 'Lowchen',
        label: 'Lowchen',
        long_label: 'Lowchen',
        facet_value: '317',
        default: false,
      },
      {
        value: 'Maltese',
        label: 'Maltese',
        long_label: 'Maltese',
        facet_value: '318',
        default: false,
      },
      {
        value: 'Manchester Terrier',
        label: 'Manchester Terrier',
        long_label: 'Manchester Terrier',
        facet_value: '319',
        default: false,
      },
      {
        value: 'Maremma Sheepdog',
        label: 'Maremma Sheepdog',
        long_label: 'Maremma Sheepdog',
        facet_value: '320',
        default: false,
      },
      {
        value: 'Mastiff',
        label: 'Mastiff',
        long_label: 'Mastiff',
        facet_value: '321',
        default: false,
      },
      {
        value: 'McNab',
        label: 'McNab',
        long_label: 'McNab',
        facet_value: '322',
        default: false,
      },
      {
        value: 'Miniature Bull Terrier',
        label: 'Miniature Bull Terrier',
        long_label: 'Miniature Bull Terrier',
        facet_value: '711',
        default: false,
      },
      {
        value: 'Miniature Dachshund',
        label: 'Miniature Dachshund',
        long_label: 'Miniature Dachshund',
        facet_value: '712',
        default: false,
      },
      {
        value: 'Miniature Pinscher',
        label: 'Miniature Pinscher',
        long_label: 'Miniature Pinscher',
        facet_value: '323',
        default: false,
      },
      {
        value: 'Miniature Poodle',
        label: 'Miniature Poodle',
        long_label: 'Miniature Poodle',
        facet_value: '716',
        default: false,
      },
      {
        value: 'Miniature Schnauzer',
        label: 'Miniature Schnauzer',
        long_label: 'Miniature Schnauzer',
        facet_value: '693',
        default: false,
      },
      {
        value: 'Mixed Breed',
        label: 'Mixed Breed',
        long_label: 'Mixed Breed',
        facet_value: '694',
        default: false,
      },
      {
        value: 'Mountain Cur',
        label: 'Mountain Cur',
        long_label: 'Mountain Cur',
        facet_value: '324',
        default: false,
      },
      {
        value: 'Mountain Dog',
        label: 'Mountain Dog',
        long_label: 'Mountain Dog',
        facet_value: '325',
        default: false,
      },
      {
        value: 'Munsterlander',
        label: 'Munsterlander',
        long_label: 'Munsterlander',
        facet_value: '326',
        default: false,
      },
      {
        value: 'Neapolitan Mastiff',
        label: 'Neapolitan Mastiff',
        long_label: 'Neapolitan Mastiff',
        facet_value: '327',
        default: false,
      },
      {
        value: 'New Guinea Singing Dog',
        label: 'New Guinea Singing Dog',
        long_label: 'New Guinea Singing Dog',
        facet_value: '328',
        default: false,
      },
      {
        value: 'Newfoundland Dog',
        label: 'Newfoundland Dog',
        long_label: 'Newfoundland Dog',
        facet_value: '329',
        default: false,
      },
      {
        value: 'Norfolk Terrier',
        label: 'Norfolk Terrier',
        long_label: 'Norfolk Terrier',
        facet_value: '330',
        default: false,
      },
      {
        value: 'Norwegian Buhund',
        label: 'Norwegian Buhund',
        long_label: 'Norwegian Buhund',
        facet_value: '331',
        default: false,
      },
      {
        value: 'Norwegian Elkhound',
        label: 'Norwegian Elkhound',
        long_label: 'Norwegian Elkhound',
        facet_value: '332',
        default: false,
      },
      {
        value: 'Norwegian Lundehund',
        label: 'Norwegian Lundehund',
        long_label: 'Norwegian Lundehund',
        facet_value: '333',
        default: false,
      },
      {
        value: 'Norwich Terrier',
        label: 'Norwich Terrier',
        long_label: 'Norwich Terrier',
        facet_value: '334',
        default: false,
      },
      {
        value: 'Nova Scotia Duck Tolling Retriever',
        label: 'Nova Scotia Duck Tolling Retriever',
        long_label: 'Nova Scotia Duck Tolling Retriever',
        facet_value: '335',
        default: false,
      },
      {
        value: 'Old English Sheepdog',
        label: 'Old English Sheepdog',
        long_label: 'Old English Sheepdog',
        facet_value: '336',
        default: false,
      },
      {
        value: 'Otterhound',
        label: 'Otterhound',
        long_label: 'Otterhound',
        facet_value: '337',
        default: false,
      },
      {
        value: 'Papillon',
        label: 'Papillon',
        long_label: 'Papillon',
        facet_value: '338',
        default: false,
      },
      {
        value: 'Parson Russell Terrier',
        label: 'Parson Russell Terrier',
        long_label: 'Parson Russell Terrier',
        facet_value: '300',
        default: false,
      },
      {
        value: 'Patterdale Terrier / Fell Terrier',
        label: 'Patterdale Terrier / Fell Terrier',
        long_label: 'Patterdale Terrier / Fell Terrier',
        facet_value: '339',
        default: false,
      },
      {
        value: 'Pekingese',
        label: 'Pekingese',
        long_label: 'Pekingese',
        facet_value: '340',
        default: false,
      },
      {
        value: 'Pembroke Welsh Corgi',
        label: 'Pembroke Welsh Corgi',
        long_label: 'Pembroke Welsh Corgi',
        facet_value: '715',
        default: false,
      },
      {
        value: 'Peruvian Inca Orchid',
        label: 'Peruvian Inca Orchid',
        long_label: 'Peruvian Inca Orchid',
        facet_value: '341',
        default: false,
      },
      {
        value: 'Petit Basset Griffon Vendeen',
        label: 'Petit Basset Griffon Vendeen',
        long_label: 'Petit Basset Griffon Vendeen',
        facet_value: '342',
        default: false,
      },
      {
        value: 'Pharaoh Hound',
        label: 'Pharaoh Hound',
        long_label: 'Pharaoh Hound',
        facet_value: '343',
        default: false,
      },
      {
        value: 'Pit Bull Terrier',
        label: 'Pit Bull Terrier',
        long_label: 'Pit Bull Terrier',
        facet_value: '344',
        default: false,
      },
      {
        value: 'Plott Hound',
        label: 'Plott Hound',
        long_label: 'Plott Hound',
        facet_value: '345',
        default: false,
      },
      {
        value: 'Pointer',
        label: 'Pointer',
        long_label: 'Pointer',
        facet_value: '347',
        default: false,
      },
      {
        value: 'Polish Lowland Sheepdog',
        label: 'Polish Lowland Sheepdog',
        long_label: 'Polish Lowland Sheepdog',
        facet_value: '348',
        default: false,
      },
      {
        value: 'Pomeranian',
        label: 'Pomeranian',
        long_label: 'Pomeranian',
        facet_value: '349',
        default: false,
      },
      {
        value: 'Poodle',
        label: 'Poodle',
        long_label: 'Poodle',
        facet_value: '350',
        default: false,
      },
      {
        value: 'Portuguese Podengo',
        label: 'Portuguese Podengo',
        long_label: 'Portuguese Podengo',
        facet_value: '346',
        default: false,
      },
      {
        value: 'Portuguese Water Dog',
        label: 'Portuguese Water Dog',
        long_label: 'Portuguese Water Dog',
        facet_value: '351',
        default: false,
      },
      {
        value: 'Presa Canario',
        label: 'Presa Canario',
        long_label: 'Presa Canario',
        facet_value: '352',
        default: false,
      },
      {
        value: 'Pug',
        label: 'Pug',
        long_label: 'Pug',
        facet_value: '353',
        default: false,
      },
      {
        value: 'Puli',
        label: 'Puli',
        long_label: 'Puli',
        facet_value: '354',
        default: false,
      },
      {
        value: 'Pumi',
        label: 'Pumi',
        long_label: 'Pumi',
        facet_value: '355',
        default: false,
      },
      {
        value: 'Pyrenean Shepherd',
        label: 'Pyrenean Shepherd',
        long_label: 'Pyrenean Shepherd',
        facet_value: '717',
        default: false,
      },
      {
        value: 'Rat Terrier',
        label: 'Rat Terrier',
        long_label: 'Rat Terrier',
        facet_value: '356',
        default: false,
      },
      {
        value: 'Redbone Coonhound',
        label: 'Redbone Coonhound',
        long_label: 'Redbone Coonhound',
        facet_value: '357',
        default: false,
      },
      {
        value: 'Retriever',
        label: 'Retriever',
        long_label: 'Retriever',
        facet_value: '358',
        default: false,
      },
      {
        value: 'Rhodesian Ridgeback',
        label: 'Rhodesian Ridgeback',
        long_label: 'Rhodesian Ridgeback',
        facet_value: '359',
        default: false,
      },
      {
        value: 'Rottweiler',
        label: 'Rottweiler',
        long_label: 'Rottweiler',
        facet_value: '360',
        default: false,
      },
      {
        value: 'Rough Collie',
        label: 'Rough Collie',
        long_label: 'Rough Collie',
        facet_value: '695',
        default: false,
      },
      {
        value: 'Saint Bernard',
        label: 'Saint Bernard',
        long_label: 'Saint Bernard',
        facet_value: '361',
        default: false,
      },
      {
        value: 'Saluki',
        label: 'Saluki',
        long_label: 'Saluki',
        facet_value: '362',
        default: false,
      },
      {
        value: 'Samoyed',
        label: 'Samoyed',
        long_label: 'Samoyed',
        facet_value: '363',
        default: false,
      },
      {
        value: 'Sarplaninac',
        label: 'Sarplaninac',
        long_label: 'Sarplaninac',
        facet_value: '364',
        default: false,
      },
      {
        value: 'Schipperke',
        label: 'Schipperke',
        long_label: 'Schipperke',
        facet_value: '365',
        default: false,
      },
      {
        value: 'Schnauzer',
        label: 'Schnauzer',
        long_label: 'Schnauzer',
        facet_value: '366',
        default: false,
      },
      {
        value: 'Scottish Deerhound',
        label: 'Scottish Deerhound',
        long_label: 'Scottish Deerhound',
        facet_value: '367',
        default: false,
      },
      {
        value: 'Scottish Terrier',
        label: 'Scottish Terrier',
        long_label: 'Scottish Terrier',
        facet_value: '368',
        default: false,
      },
      {
        value: 'Sealyham Terrier',
        label: 'Sealyham Terrier',
        long_label: 'Sealyham Terrier',
        facet_value: '369',
        default: false,
      },
      {
        value: 'Setter',
        label: 'Setter',
        long_label: 'Setter',
        facet_value: '678',
        default: false,
      },
      {
        value: 'Shar-Pei',
        label: 'Shar-Pei',
        long_label: 'Shar-Pei',
        facet_value: '370',
        default: false,
      },
      {
        value: 'Sheep Dog',
        label: 'Sheep Dog',
        long_label: 'Sheep Dog',
        facet_value: '371',
        default: false,
      },
      {
        value: 'Shepherd',
        label: 'Shepherd',
        long_label: 'Shepherd',
        facet_value: '372',
        default: false,
      },
      {
        value: 'Shetland Sheepdog / Sheltie',
        label: 'Shetland Sheepdog / Sheltie',
        long_label: 'Shetland Sheepdog / Sheltie',
        facet_value: '373',
        default: false,
      },
      {
        value: 'Shiba Inu',
        label: 'Shiba Inu',
        long_label: 'Shiba Inu',
        facet_value: '374',
        default: false,
      },
      {
        value: 'Shih Tzu',
        label: 'Shih Tzu',
        long_label: 'Shih Tzu',
        facet_value: '375',
        default: false,
      },
      {
        value: 'Siberian Husky',
        label: 'Siberian Husky',
        long_label: 'Siberian Husky',
        facet_value: '376',
        default: false,
      },
      {
        value: 'Silky Terrier',
        label: 'Silky Terrier',
        long_label: 'Silky Terrier',
        facet_value: '377',
        default: false,
      },
      {
        value: 'Skye Terrier',
        label: 'Skye Terrier',
        long_label: 'Skye Terrier',
        facet_value: '378',
        default: false,
      },
      {
        value: 'Sloughi',
        label: 'Sloughi',
        long_label: 'Sloughi',
        facet_value: '379',
        default: false,
      },
      {
        value: 'Smooth Collie',
        label: 'Smooth Collie',
        long_label: 'Smooth Collie',
        facet_value: '696',
        default: false,
      },
      {
        value: 'Smooth Fox Terrier',
        label: 'Smooth Fox Terrier',
        long_label: 'Smooth Fox Terrier',
        facet_value: '380',
        default: false,
      },
      {
        value: 'South Russian Ovtcharka',
        label: 'South Russian Ovtcharka',
        long_label: 'South Russian Ovtcharka',
        facet_value: '381',
        default: false,
      },
      {
        value: 'Spaniel',
        label: 'Spaniel',
        long_label: 'Spaniel',
        facet_value: '382',
        default: false,
      },
      {
        value: 'Spanish Water Dog',
        label: 'Spanish Water Dog',
        long_label: 'Spanish Water Dog',
        facet_value: '697',
        default: false,
      },
      {
        value: 'Spinone Italiano',
        label: 'Spinone Italiano',
        long_label: 'Spinone Italiano',
        facet_value: '298',
        default: false,
      },
      {
        value: 'Spitz',
        label: 'Spitz',
        long_label: 'Spitz',
        facet_value: '383',
        default: false,
      },
      {
        value: 'Staffordshire Bull Terrier',
        label: 'Staffordshire Bull Terrier',
        long_label: 'Staffordshire Bull Terrier',
        facet_value: '384',
        default: false,
      },
      {
        value: 'Standard Poodle',
        label: 'Standard Poodle',
        long_label: 'Standard Poodle',
        facet_value: '385',
        default: false,
      },
      {
        value: 'Standard Schnauzer',
        label: 'Standard Schnauzer',
        long_label: 'Standard Schnauzer',
        facet_value: '698',
        default: false,
      },
      {
        value: 'Sussex Spaniel',
        label: 'Sussex Spaniel',
        long_label: 'Sussex Spaniel',
        facet_value: '386',
        default: false,
      },
      {
        value: 'Swedish Vallhund',
        label: 'Swedish Vallhund',
        long_label: 'Swedish Vallhund',
        facet_value: '387',
        default: false,
      },
      {
        value: 'Terrier',
        label: 'Terrier',
        long_label: 'Terrier',
        facet_value: '388',
        default: false,
      },
      {
        value: 'Thai Ridgeback',
        label: 'Thai Ridgeback',
        long_label: 'Thai Ridgeback',
        facet_value: '389',
        default: false,
      },
      {
        value: 'Tibetan Mastiff',
        label: 'Tibetan Mastiff',
        long_label: 'Tibetan Mastiff',
        facet_value: '390',
        default: false,
      },
      {
        value: 'Tibetan Spaniel',
        label: 'Tibetan Spaniel',
        long_label: 'Tibetan Spaniel',
        facet_value: '391',
        default: false,
      },
      {
        value: 'Tibetan Terrier',
        label: 'Tibetan Terrier',
        long_label: 'Tibetan Terrier',
        facet_value: '392',
        default: false,
      },
      {
        value: 'Tosa Inu',
        label: 'Tosa Inu',
        long_label: 'Tosa Inu',
        facet_value: '393',
        default: false,
      },
      {
        value: 'Toy Fox Terrier',
        label: 'Toy Fox Terrier',
        long_label: 'Toy Fox Terrier',
        facet_value: '394',
        default: false,
      },
      {
        value: 'Toy Manchester Terrier',
        label: 'Toy Manchester Terrier',
        long_label: 'Toy Manchester Terrier',
        facet_value: '714',
        default: false,
      },
      {
        value: 'Treeing Walker Coonhound',
        label: 'Treeing Walker Coonhound',
        long_label: 'Treeing Walker Coonhound',
        facet_value: '395',
        default: false,
      },
      {
        value: 'Vizsla',
        label: 'Vizsla',
        long_label: 'Vizsla',
        facet_value: '396',
        default: false,
      },
      {
        value: 'Weimaraner',
        label: 'Weimaraner',
        long_label: 'Weimaraner',
        facet_value: '397',
        default: false,
      },
      {
        value: 'Welsh Springer Spaniel',
        label: 'Welsh Springer Spaniel',
        long_label: 'Welsh Springer Spaniel',
        facet_value: '399',
        default: false,
      },
      {
        value: 'Welsh Terrier',
        label: 'Welsh Terrier',
        long_label: 'Welsh Terrier',
        facet_value: '400',
        default: false,
      },
      {
        value: 'West Highland White Terrier / Westie',
        label: 'West Highland White Terrier / Westie',
        long_label: 'West Highland White Terrier / Westie',
        facet_value: '401',
        default: false,
      },
      {
        value: 'Wheaten Terrier',
        label: 'Wheaten Terrier',
        long_label: 'Wheaten Terrier',
        facet_value: '402',
        default: false,
      },
      {
        value: 'Whippet',
        label: 'Whippet',
        long_label: 'Whippet',
        facet_value: '403',
        default: false,
      },
      {
        value: 'White German Shepherd',
        label: 'White German Shepherd',
        long_label: 'White German Shepherd',
        facet_value: '404',
        default: false,
      },
      {
        value: 'Wire Fox Terrier',
        label: 'Wire Fox Terrier',
        long_label: 'Wire Fox Terrier',
        facet_value: '405',
        default: false,
      },
      {
        value: 'Wirehaired Dachshund',
        label: 'Wirehaired Dachshund',
        long_label: 'Wirehaired Dachshund',
        facet_value: '699',
        default: false,
      },
      {
        value: 'Wirehaired Pointing Griffon',
        label: 'Wirehaired Pointing Griffon',
        long_label: 'Wirehaired Pointing Griffon',
        facet_value: '406',
        default: false,
      },
      {
        value: 'Wirehaired Terrier',
        label: 'Wirehaired Terrier',
        long_label: 'Wirehaired Terrier',
        facet_value: '407',
        default: false,
      },
      {
        value: 'Xoloitzcuintli / Mexican Hairless',
        label: 'Xoloitzcuintli / Mexican Hairless',
        long_label: 'Xoloitzcuintli / Mexican Hairless',
        facet_value: '408',
        default: false,
      },
      {
        value: 'Yellow Labrador Retriever',
        label: 'Yellow Labrador Retriever',
        long_label: 'Yellow Labrador Retriever',
        facet_value: '409',
        default: false,
      },
      {
        value: 'Yorkshire Terrier',
        label: 'Yorkshire Terrier',
        long_label: 'Yorkshire Terrier',
        facet_value: '410',
        default: false,
      },
    ],
  },
};

export default dogFilters;
