const birdFilters = {
  breed: {
    name: 'breed',
    label: 'Breed',
    display: true,
    options: [
      {
        value: 'African Grey',
        label: 'African Grey',
        long_label: 'African Grey',
        facet_value: '1',
        default: false,
      },
      {
        value: 'Amazon',
        label: 'Amazon',
        long_label: 'Amazon',
        facet_value: '2',
        default: false,
      },
      {
        value: 'Brotogeris',
        label: 'Brotogeris',
        long_label: 'Brotogeris',
        facet_value: '3',
        default: false,
      },
      {
        value: 'Budgie / Budgerigar',
        label: 'Budgie / Budgerigar',
        long_label: 'Budgie / Budgerigar',
        facet_value: '4',
        default: false,
      },
      {
        value: 'Button-Quail',
        label: 'Button-Quail',
        long_label: 'Button-Quail',
        facet_value: '21',
        default: false,
      },
      {
        value: 'Caique',
        label: 'Caique',
        long_label: 'Caique',
        facet_value: '8',
        default: false,
      },
      {
        value: 'Canary',
        label: 'Canary',
        long_label: 'Canary',
        facet_value: '36',
        default: false,
      },
      {
        value: 'Chicken',
        label: 'Chicken',
        long_label: 'Chicken',
        facet_value: '22',
        default: false,
      },
      {
        value: 'Cockatiel',
        label: 'Cockatiel',
        long_label: 'Cockatiel',
        facet_value: '5',
        default: false,
      },
      {
        value: 'Cockatoo',
        label: 'Cockatoo',
        long_label: 'Cockatoo',
        facet_value: '6',
        default: false,
      },
      {
        value: 'Conure',
        label: 'Conure',
        long_label: 'Conure',
        facet_value: '7',
        default: false,
      },
      {
        value: 'Dove',
        label: 'Dove',
        long_label: 'Dove',
        facet_value: '38',
        default: false,
      },
      {
        value: 'Duck',
        label: 'Duck',
        long_label: 'Duck',
        facet_value: '24',
        default: false,
      },
      {
        value: 'Eclectus',
        label: 'Eclectus',
        long_label: 'Eclectus',
        facet_value: '9',
        default: false,
      },
      {
        value: 'Emu',
        label: 'Emu',
        long_label: 'Emu',
        facet_value: '23',
        default: false,
      },
      {
        value: 'Finch',
        label: 'Finch',
        long_label: 'Finch',
        facet_value: '37',
        default: false,
      },
      {
        value: 'Goose',
        label: 'Goose',
        long_label: 'Goose',
        facet_value: '25',
        default: false,
      },
      {
        value: 'Guinea Fowl',
        label: 'Guinea Fowl',
        long_label: 'Guinea Fowl',
        facet_value: '26',
        default: false,
      },
      {
        value: 'Kakariki',
        label: 'Kakariki',
        long_label: 'Kakariki',
        facet_value: '10',
        default: false,
      },
      {
        value: 'Lory / Lorikeet',
        label: 'Lory / Lorikeet',
        long_label: 'Lory / Lorikeet',
        facet_value: '11',
        default: false,
      },
      {
        value: 'Lovebird',
        label: 'Lovebird',
        long_label: 'Lovebird',
        facet_value: '12',
        default: false,
      },
      {
        value: 'Macaw',
        label: 'Macaw',
        long_label: 'Macaw',
        facet_value: '13',
        default: false,
      },
      {
        value: 'Ostrich',
        label: 'Ostrich',
        long_label: 'Ostrich',
        facet_value: '27',
        default: false,
      },
      {
        value: 'Parakeet (Other)',
        label: 'Parakeet (Other)',
        long_label: 'Parakeet (Other)',
        facet_value: '40',
        default: false,
      },
      {
        value: 'Parrot (Other)',
        label: 'Parrot (Other)',
        long_label: 'Parrot (Other)',
        facet_value: '14',
        default: false,
      },
      {
        value: 'Parrotlet',
        label: 'Parrotlet',
        long_label: 'Parrotlet',
        facet_value: '15',
        default: false,
      },
      {
        value: 'Peacock / Peafowl',
        label: 'Peacock / Peafowl',
        long_label: 'Peacock / Peafowl',
        facet_value: '29',
        default: false,
      },
      {
        value: 'Pheasant',
        label: 'Pheasant',
        long_label: 'Pheasant',
        facet_value: '30',
        default: false,
      },
      {
        value: 'Pigeon',
        label: 'Pigeon',
        long_label: 'Pigeon',
        facet_value: '39',
        default: false,
      },
      {
        value: 'Pionus',
        label: 'Pionus',
        long_label: 'Pionus',
        facet_value: '16',
        default: false,
      },
      {
        value: 'Poicephalus / Senegal',
        label: 'Poicephalus / Senegal',
        long_label: 'Poicephalus / Senegal',
        facet_value: '17',
        default: false,
      },
      {
        value: 'Quail',
        label: 'Quail',
        long_label: 'Quail',
        facet_value: '31',
        default: false,
      },
      {
        value: 'Quaker Parakeet',
        label: 'Quaker Parakeet',
        long_label: 'Quaker Parakeet',
        facet_value: '18',
        default: false,
      },
      {
        value: 'Rhea',
        label: 'Rhea',
        long_label: 'Rhea',
        facet_value: '32',
        default: false,
      },
      {
        value: 'Ringneck / Psittacula',
        label: 'Ringneck / Psittacula',
        long_label: 'Ringneck / Psittacula',
        facet_value: '19',
        default: false,
      },
      {
        value: 'Rosella',
        label: 'Rosella',
        long_label: 'Rosella',
        facet_value: '20',
        default: false,
      },
      {
        value: 'Swan',
        label: 'Swan',
        long_label: 'Swan',
        facet_value: '33',
        default: false,
      },
      {
        value: 'Toucan',
        label: 'Toucan',
        long_label: 'Toucan',
        facet_value: '34',
        default: false,
      },
      {
        value: 'Turkey',
        label: 'Turkey',
        long_label: 'Turkey',
        facet_value: '35',
        default: false,
      },
    ],
  },
};

export default birdFilters;
