const catFilters = {
  age: {
    name: 'age',
    label: 'Age',
    display: true,
    options: [
      {
        value: 'Baby',
        label: 'Kitten',
        long_label: 'Kitten',
        default: false,
      },
      {
        value: 'Young',
        label: 'Young',
        long_label: 'Young',
        default: false,
      },
      {
        value: 'Adult',
        label: 'Adult',
        long_label: 'Adult',
        default: false,
      },
      {
        value: 'Senior',
        label: 'Senior',
        long_label: 'Senior',
        default: false,
      },
    ],
  },
  breed: {
    name: 'breed',
    label: 'Breed',
    display: true,
    options: [
      {
        value: 'Abyssinian',
        label: 'Abyssinian',
        long_label: 'Abyssinian',
        facet_value: '41',
        default: false,
      },
      {
        value: 'American Bobtail',
        label: 'American Bobtail',
        long_label: 'American Bobtail',
        facet_value: '49',
        default: false,
      },
      {
        value: 'American Curl',
        label: 'American Curl',
        long_label: 'American Curl',
        facet_value: '42',
        default: false,
      },
      {
        value: 'American Shorthair',
        label: 'American Shorthair',
        long_label: 'American Shorthair',
        facet_value: '43',
        default: false,
      },
      {
        value: 'American Wirehair',
        label: 'American Wirehair',
        long_label: 'American Wirehair',
        facet_value: '44',
        default: false,
      },
      {
        value: 'Applehead Siamese',
        label: 'Applehead Siamese',
        long_label: 'Applehead Siamese',
        facet_value: '45',
        default: false,
      },
      {
        value: 'Balinese',
        label: 'Balinese',
        long_label: 'Balinese',
        facet_value: '46',
        default: false,
      },
      {
        value: 'Bengal',
        label: 'Bengal',
        long_label: 'Bengal',
        facet_value: '47',
        default: false,
      },
      {
        value: 'Birman',
        label: 'Birman',
        long_label: 'Birman',
        facet_value: '48',
        default: false,
      },
      {
        value: 'Bombay',
        label: 'Bombay',
        long_label: 'Bombay',
        facet_value: '50',
        default: false,
      },
      {
        value: 'British Shorthair',
        label: 'British Shorthair',
        long_label: 'British Shorthair',
        facet_value: '51',
        default: false,
      },
      {
        value: 'Burmese',
        label: 'Burmese',
        long_label: 'Burmese',
        facet_value: '52',
        default: false,
      },
      {
        value: 'Burmilla',
        label: 'Burmilla',
        long_label: 'Burmilla',
        facet_value: '53',
        default: false,
      },
      {
        value: 'Calico',
        label: 'Calico',
        long_label: 'Calico',
        facet_value: '54',
        default: false,
      },
      {
        value: 'Canadian Hairless',
        label: 'Canadian Hairless',
        long_label: 'Canadian Hairless',
        facet_value: '55',
        default: false,
      },
      {
        value: 'Chartreux',
        label: 'Chartreux',
        long_label: 'Chartreux',
        facet_value: '56',
        default: false,
      },
      {
        value: 'Chausie',
        label: 'Chausie',
        long_label: 'Chausie',
        facet_value: '57',
        default: false,
      },
      {
        value: 'Chinchilla',
        label: 'Chinchilla',
        long_label: 'Chinchilla',
        facet_value: '58',
        default: false,
      },
      {
        value: 'Cornish Rex',
        label: 'Cornish Rex',
        long_label: 'Cornish Rex',
        facet_value: '59',
        default: false,
      },
      {
        value: 'Cymric',
        label: 'Cymric',
        long_label: 'Cymric',
        facet_value: '60',
        default: false,
      },
      {
        value: 'Devon Rex',
        label: 'Devon Rex',
        long_label: 'Devon Rex',
        facet_value: '61',
        default: false,
      },
      {
        value: 'Dilute Calico',
        label: 'Dilute Calico',
        long_label: 'Dilute Calico',
        facet_value: '62',
        default: false,
      },
      {
        value: 'Dilute Tortoiseshell',
        label: 'Dilute Tortoiseshell',
        long_label: 'Dilute Tortoiseshell',
        facet_value: '63',
        default: false,
      },
      {
        value: 'Domestic Long Hair',
        label: 'Domestic Long Hair',
        long_label: 'Domestic Long Hair',
        facet_value: '64',
        default: false,
      },
      {
        value: 'Domestic Medium Hair',
        label: 'Domestic Medium Hair',
        long_label: 'Domestic Medium Hair',
        facet_value: '75',
        default: false,
      },
      {
        value: 'Domestic Short Hair',
        label: 'Domestic Short Hair',
        long_label: 'Domestic Short Hair',
        facet_value: '86',
        default: false,
      },
      {
        value: 'Egyptian Mau',
        label: 'Egyptian Mau',
        long_label: 'Egyptian Mau',
        facet_value: '98',
        default: false,
      },
      {
        value: 'Exotic Shorthair',
        label: 'Exotic Shorthair',
        long_label: 'Exotic Shorthair',
        facet_value: '99',
        default: false,
      },
      {
        value: 'Extra-Toes Cat / Hemingway Polydactyl',
        label: 'Extra-Toes Cat / Hemingway Polydactyl',
        long_label: 'Extra-Toes Cat / Hemingway Polydactyl',
        facet_value: '100',
        default: false,
      },
      {
        value: 'Havana',
        label: 'Havana',
        long_label: 'Havana',
        facet_value: '101',
        default: false,
      },
      {
        value: 'Himalayan',
        label: 'Himalayan',
        long_label: 'Himalayan',
        facet_value: '102',
        default: false,
      },
      {
        value: 'Japanese Bobtail',
        label: 'Japanese Bobtail',
        long_label: 'Japanese Bobtail',
        facet_value: '103',
        default: false,
      },
      {
        value: 'Javanese',
        label: 'Javanese',
        long_label: 'Javanese',
        facet_value: '104',
        default: false,
      },
      {
        value: 'Korat',
        label: 'Korat',
        long_label: 'Korat',
        facet_value: '105',
        default: false,
      },
      {
        value: 'LaPerm',
        label: 'LaPerm',
        long_label: 'LaPerm',
        facet_value: '106',
        default: false,
      },
      {
        value: 'Maine Coon',
        label: 'Maine Coon',
        long_label: 'Maine Coon',
        facet_value: '107',
        default: false,
      },
      {
        value: 'Manx',
        label: 'Manx',
        long_label: 'Manx',
        facet_value: '108',
        default: false,
      },
      {
        value: 'Munchkin',
        label: 'Munchkin',
        long_label: 'Munchkin',
        facet_value: '109',
        default: false,
      },
      {
        value: 'Nebelung',
        label: 'Nebelung',
        long_label: 'Nebelung',
        facet_value: '110',
        default: false,
      },
      {
        value: 'Norwegian Forest Cat',
        label: 'Norwegian Forest Cat',
        long_label: 'Norwegian Forest Cat',
        facet_value: '111',
        default: false,
      },
      {
        value: 'Ocicat',
        label: 'Ocicat',
        long_label: 'Ocicat',
        facet_value: '112',
        default: false,
      },
      {
        value: 'Oriental Long Hair',
        label: 'Oriental Long Hair',
        long_label: 'Oriental Long Hair',
        facet_value: '113',
        default: false,
      },
      {
        value: 'Oriental Short Hair',
        label: 'Oriental Short Hair',
        long_label: 'Oriental Short Hair',
        facet_value: '114',
        default: false,
      },
      {
        value: 'Oriental Tabby',
        label: 'Oriental Tabby',
        long_label: 'Oriental Tabby',
        facet_value: '115',
        default: false,
      },
      {
        value: 'Persian',
        label: 'Persian',
        long_label: 'Persian',
        facet_value: '116',
        default: false,
      },
      {
        value: 'Pixiebob',
        label: 'Pixiebob',
        long_label: 'Pixiebob',
        facet_value: '117',
        default: false,
      },
      {
        value: 'Ragamuffin',
        label: 'Ragamuffin',
        long_label: 'Ragamuffin',
        facet_value: '118',
        default: false,
      },
      {
        value: 'Ragdoll',
        label: 'Ragdoll',
        long_label: 'Ragdoll',
        facet_value: '119',
        default: false,
      },
      {
        value: 'Russian Blue',
        label: 'Russian Blue',
        long_label: 'Russian Blue',
        facet_value: '120',
        default: false,
      },
      {
        value: 'Scottish Fold',
        label: 'Scottish Fold',
        long_label: 'Scottish Fold',
        facet_value: '121',
        default: false,
      },
      {
        value: 'Selkirk Rex',
        label: 'Selkirk Rex',
        long_label: 'Selkirk Rex',
        facet_value: '122',
        default: false,
      },
      {
        value: 'Siamese',
        label: 'Siamese',
        long_label: 'Siamese',
        facet_value: '123',
        default: false,
      },
      {
        value: 'Siberian',
        label: 'Siberian',
        long_label: 'Siberian',
        facet_value: '124',
        default: false,
      },
      {
        value: 'Silver',
        label: 'Silver',
        long_label: 'Silver',
        facet_value: '125',
        default: false,
      },
      {
        value: 'Singapura',
        label: 'Singapura',
        long_label: 'Singapura',
        facet_value: '126',
        default: false,
      },
      {
        value: 'Snowshoe',
        label: 'Snowshoe',
        long_label: 'Snowshoe',
        facet_value: '127',
        default: false,
      },
      {
        value: 'Somali',
        label: 'Somali',
        long_label: 'Somali',
        facet_value: '128',
        default: false,
      },
      {
        value: 'Sphynx / Hairless Cat',
        label: 'Sphynx / Hairless Cat',
        long_label: 'Sphynx / Hairless Cat',
        facet_value: '129',
        default: false,
      },
      {
        value: 'Tabby',
        label: 'Tabby',
        long_label: 'Tabby',
        facet_value: '130',
        default: false,
      },
      {
        value: 'Tiger',
        label: 'Tiger',
        long_label: 'Tiger',
        facet_value: '137',
        default: false,
      },
      {
        value: 'Tonkinese',
        label: 'Tonkinese',
        long_label: 'Tonkinese',
        facet_value: '138',
        default: false,
      },
      {
        value: 'Torbie',
        label: 'Torbie',
        long_label: 'Torbie',
        facet_value: '139',
        default: false,
      },
      {
        value: 'Tortoiseshell',
        label: 'Tortoiseshell',
        long_label: 'Tortoiseshell',
        facet_value: '140',
        default: false,
      },
      {
        value: 'Turkish Angora',
        label: 'Turkish Angora',
        long_label: 'Turkish Angora',
        facet_value: '141',
        default: false,
      },
      {
        value: 'Turkish Van',
        label: 'Turkish Van',
        long_label: 'Turkish Van',
        facet_value: '142',
        default: false,
      },
      {
        value: 'Tuxedo',
        label: 'Tuxedo',
        long_label: 'Tuxedo',
        facet_value: '143',
        default: false,
      },
      {
        value: 'York Chocolate',
        label: 'York Chocolate',
        long_label: 'York Chocolate',
        facet_value: '718',
        default: false,
      },
    ],
  },
};

export default catFilters;
