const otherFilters = {
  breed: {
    name: 'breed',
    label: 'Breed',
    display: true,
    options: [
      {
        value: 'Asian Box',
        label: 'Asian Box',
        long_label: 'Asian Box',
        facet_value: '538',
        default: false,
      },
      {
        value: 'Ball Python',
        label: 'Ball Python',
        long_label: 'Ball Python',
        facet_value: '549',
        default: false,
      },
      {
        value: 'Bearded Dragon',
        label: 'Bearded Dragon',
        long_label: 'Bearded Dragon',
        facet_value: '672',
        default: false,
      },
      {
        value: 'Boa',
        label: 'Boa',
        long_label: 'Boa',
        facet_value: '547',
        default: false,
      },
      {
        value: 'Boa Constrictor',
        label: 'Boa Constrictor',
        long_label: 'Boa Constrictor',
        facet_value: '546',
        default: false,
      },
      {
        value: 'Box',
        label: 'Box',
        long_label: 'Box',
        facet_value: '540',
        default: false,
      },
      {
        value: 'Bull',
        label: 'Bull',
        long_label: 'Bull',
        facet_value: '553',
        default: false,
      },
      {
        value: 'Bullfrog',
        label: 'Bullfrog',
        long_label: 'Bullfrog',
        facet_value: '512',
        default: false,
      },
      {
        value: 'Burmese Python',
        label: 'Burmese Python',
        long_label: 'Burmese Python',
        facet_value: '548',
        default: false,
      },
      {
        value: 'Chameleon',
        label: 'Chameleon',
        long_label: 'Chameleon',
        facet_value: '675',
        default: false,
      },
      {
        value: 'Corn / Rat',
        label: 'Corn / Rat',
        long_label: 'Corn / Rat',
        facet_value: '552',
        default: false,
      },
      {
        value: 'Eastern Box',
        label: 'Eastern Box',
        long_label: 'Eastern Box',
        facet_value: '535',
        default: false,
      },
      {
        value: 'Fire Salamander',
        label: 'Fire Salamander',
        long_label: 'Fire Salamander',
        facet_value: '523',
        default: false,
      },
      {
        value: 'Fire-Bellied',
        label: 'Fire-Bellied',
        long_label: 'Fire-Bellied',
        facet_value: '517',
        default: false,
      },
      {
        value: 'Fire-Bellied Newt',
        label: 'Fire-Bellied Newt',
        long_label: 'Fire-Bellied Newt',
        facet_value: '524',
        default: false,
      },
      {
        value: 'Florida Box',
        label: 'Florida Box',
        long_label: 'Florida Box',
        facet_value: '537',
        default: false,
      },
      {
        value: 'Freshwater Fish',
        label: 'Freshwater Fish',
        long_label: 'Freshwater Fish',
        facet_value: '520',
        default: false,
      },
      {
        value: 'Frog',
        label: 'Frog',
        long_label: 'Frog',
        facet_value: '511',
        default: false,
      },
      {
        value: 'Garter / Ribbon',
        label: 'Garter / Ribbon',
        long_label: 'Garter / Ribbon',
        facet_value: '554',
        default: false,
      },
      {
        value: 'Gecko',
        label: 'Gecko',
        long_label: 'Gecko',
        facet_value: '674',
        default: false,
      },
      {
        value: 'Goldfish',
        label: 'Goldfish',
        long_label: 'Goldfish',
        facet_value: '519',
        default: false,
      },
      {
        value: 'Hermit Crab',
        label: 'Hermit Crab',
        long_label: 'Hermit Crab',
        facet_value: '669',
        default: false,
      },
      {
        value: 'Horned Frog',
        label: 'Horned Frog',
        long_label: 'Horned Frog',
        facet_value: '513',
        default: false,
      },
      {
        value: 'Iguana',
        label: 'Iguana',
        long_label: 'Iguana',
        facet_value: '671',
        default: false,
      },
      {
        value: 'King / Milk',
        label: 'King / Milk',
        long_label: 'King / Milk',
        facet_value: '551',
        default: false,
      },
      {
        value: 'Leopard',
        label: 'Leopard',
        long_label: 'Leopard',
        facet_value: '544',
        default: false,
      },
      {
        value: 'Leopard Frog',
        label: 'Leopard Frog',
        long_label: 'Leopard Frog',
        facet_value: '515',
        default: false,
      },
      {
        value: 'Lizard',
        label: 'Lizard',
        long_label: 'Lizard',
        facet_value: '670',
        default: false,
      },
      {
        value: 'Mississippi Map Turtle',
        label: 'Mississippi Map Turtle',
        long_label: 'Mississippi Map Turtle',
        facet_value: '706',
        default: false,
      },
      {
        value: 'Monitor',
        label: 'Monitor',
        long_label: 'Monitor',
        facet_value: '676',
        default: false,
      },
      {
        value: 'Mud',
        label: 'Mud',
        long_label: 'Mud',
        facet_value: '531',
        default: false,
      },
      {
        value: 'Musk',
        label: 'Musk',
        long_label: 'Musk',
        facet_value: '532',
        default: false,
      },
      {
        value: 'Oregon Newt',
        label: 'Oregon Newt',
        long_label: 'Oregon Newt',
        facet_value: '526',
        default: false,
      },
      {
        value: 'Ornamental Box',
        label: 'Ornamental Box',
        long_label: 'Ornamental Box',
        facet_value: '536',
        default: false,
      },
      {
        value: 'Other',
        label: 'Other',
        long_label: 'Other',
        facet_value: '708',
        default: false,
      },
      {
        value: 'Paddle Tailed Newt',
        label: 'Paddle Tailed Newt',
        long_label: 'Paddle Tailed Newt',
        facet_value: '525',
        default: false,
      },
      {
        value: 'Painted',
        label: 'Painted',
        long_label: 'Painted',
        facet_value: '530',
        default: false,
      },
      {
        value: 'Python',
        label: 'Python',
        long_label: 'Python',
        facet_value: '550',
        default: false,
      },
      {
        value: 'Red Foot',
        label: 'Red Foot',
        long_label: 'Red Foot',
        facet_value: '542',
        default: false,
      },
      {
        value: 'Red-Eared Slider',
        label: 'Red-Eared Slider',
        long_label: 'Red-Eared Slider',
        facet_value: '528',
        default: false,
      },
      {
        value: 'Russian',
        label: 'Russian',
        long_label: 'Russian',
        facet_value: '541',
        default: false,
      },
      {
        value: 'Saltwater Fish',
        label: 'Saltwater Fish',
        long_label: 'Saltwater Fish',
        facet_value: '521',
        default: false,
      },
      {
        value: 'Scorpion',
        label: 'Scorpion',
        long_label: 'Scorpion',
        facet_value: '668',
        default: false,
      },
      {
        value: 'Snake',
        label: 'Snake',
        long_label: 'Snake',
        facet_value: '555',
        default: false,
      },
      {
        value: 'Snapping',
        label: 'Snapping',
        long_label: 'Snapping',
        facet_value: '533',
        default: false,
      },
      {
        value: 'Soft Shell',
        label: 'Soft Shell',
        long_label: 'Soft Shell',
        facet_value: '534',
        default: false,
      },
      {
        value: 'Southern',
        label: 'Southern',
        long_label: 'Southern',
        facet_value: '518',
        default: false,
      },
      {
        value: 'Sulcata',
        label: 'Sulcata',
        long_label: 'Sulcata',
        facet_value: '543',
        default: false,
      },
      {
        value: 'Tarantula',
        label: 'Tarantula',
        long_label: 'Tarantula',
        facet_value: '667',
        default: false,
      },
      {
        value: 'Three-Toed Box',
        label: 'Three-Toed Box',
        long_label: 'Three-Toed Box',
        facet_value: '539',
        default: false,
      },
      {
        value: 'Tiger Salamander',
        label: 'Tiger Salamander',
        long_label: 'Tiger Salamander',
        facet_value: '522',
        default: false,
      },
      {
        value: 'Toad',
        label: 'Toad',
        long_label: 'Toad',
        facet_value: '516',
        default: false,
      },
      {
        value: 'Tortoise',
        label: 'Tortoise',
        long_label: 'Tortoise',
        facet_value: '545',
        default: false,
      },
      {
        value: 'Tree Frog',
        label: 'Tree Frog',
        long_label: 'Tree Frog',
        facet_value: '514',
        default: false,
      },
      {
        value: 'Turtle',
        label: 'Turtle',
        long_label: 'Turtle',
        facet_value: '527',
        default: false,
      },
      {
        value: 'Uromastyx',
        label: 'Uromastyx',
        long_label: 'Uromastyx',
        facet_value: '673',
        default: false,
      },
      {
        value: 'Water Dragon',
        label: 'Water Dragon',
        long_label: 'Water Dragon',
        facet_value: '709',
        default: false,
      },
      {
        value: 'Yellow-Bellied Slider',
        label: 'Yellow-Bellied Slider',
        long_label: 'Yellow-Bellied Slider',
        facet_value: '529',
        default: false,
      },
    ],
  },
};

export default otherFilters;
